# Generated by Django 3.0.6 on 2020-05-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emploee_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('hire_date', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('commission_pct', models.FloatField()),
                ('manager_id', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Department')),
                ('job_id', models.ManyToManyField(to='workers.Job')),
            ],
        ),
    ]
